In [1]:
import numpy as np 
import csv
import pandas as pd

------------------------------------

# Data Preprocessing

In [2]:
input_path = "Example.tsv"
input_ds = pd.read_csv(input_path, header = None, sep="\t")

In [3]:
input_ds.head()

0         1         2   3
0  A -1.525735  1.674080 NaN
1  A  6.069158  5.152899 NaN
2  A -4.146633  1.081567 NaN
3  A -4.994697  2.974933 NaN
4  A -0.837513 -1.655131 NaN

In [4]:
n_cols = len(input_ds.columns)
input_ds = input_ds.drop(n_cols-1, axis=1) #delete the last column because its NaN for all rows
#insert bias 
input_ds.insert(1,None,np.ones(input_ds.shape[0]))

In [5]:
input_ds.head()

0.0  NaN        1.0       2.0
0    A   1.0 -1.525735  1.674080
1    A   1.0  6.069158  5.152899
2    A   1.0 -4.146633  1.081567
3    A   1.0 -4.994697  2.974933
4    A   1.0 -0.837513 -1.655131

In [6]:
n_cols = len(input_ds.columns)
print("Number of columns:", n_cols)

Number of columns: 4


In [8]:
#initiate empty list for column name
col_name = []

#naming scheme starts with x1 because we will concatenate
#x0 = 1 vector in the list later 
for i in range(n_cols):
    #last column is the target value
    if (i == 0):
        col_name.append('labels')
    else:
        col_name.append('x_{}'.format(i-1))
        
print(col_name)

['labels', 'x_0', 'x_1', 'x_2']


In [9]:
#assigning column names to data set
input_ds.columns = col_name
print (input_ds.head())

  labels  x_0       x_1       x_2
0      A  1.0 -1.525735  1.674080
1      A  1.0  6.069158  5.152899
2      A  1.0 -4.146633  1.081567
3      A  1.0 -4.994697  2.974933
4      A  1.0 -0.837513 -1.655131


In [10]:
#setting up label vector, if A then 1 else 0
y = np.where(input_ds['labels']=='A',1,0)
print(y)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [17]:
x = input_ds.iloc[:,1:n_cols]
x = np.squeeze(np.asarray(x))
print(x)
print("Shape of x:",x.shape)

[[ 1.       -1.525735  1.67408 ]
 [ 1.        6.069158  5.152899]
 [ 1.       -4.146633  1.081567]
 ...
 [ 1.        0.133127  0.253598]
 [ 1.        2.430233 -5.353957]
 [ 1.        3.307525 -6.887782]]
Shape of x: (400, 3)


-----------------------------------

# Helper Function

In [ ]:
def acti_func(w,x):
    y_pred = np.sum(np.dot(x,w))
    if (y_pred>0):
        return 1
    else:
        return 0
    
def error_rate(y,w,x):
    